package bootstrap

import (
	"strings"

	"github.com/gofiber/fiber/v2"
)

// The gateway had a REST surface — auth, the generic capability bridge,
// webhook management — and nothing that described it. An integrator building
// against it had to read this package's source, and no tool (a client
// generator, a Swagger UI, a contract test) had anything to consume.
//
// This is deliberately a hand-built document, not one generated from
// `sannad.kernel.v1.Capabilities` via grpc-gateway's proto annotations. That
// proto describes one generic RPC — Call(capability, opaque bytes) — and a
// codegen'd REST projection of it would describe exactly that: one path
// with an opaque body. The actual REST surface has more shape than the proto
// does (typed auth payloads, per-field webhook endpoint schemas), and none of
// it changes when a module registers or exposes a new capability — a
// capability's own request and response shape is that module's contract to
// publish, not the kernel's to guess. So the document below is what the
// kernel itself can honestly describe: its own fixed endpoints, precisely,
// and the capability dispatch endpoint's request truthfully documented as
// what it is — a reference and an opaque JSON payload, exactly as the proto
// already states.
//
// This is intentionally not wired to update itself from RegisterAuthenticatedRoutes:
// entrypoint-registered routes are named by the entrypoint, not the kernel, so
// the kernel cannot describe their schemas either — the same reason capability
// payloads are opaque. An entrypoint wanting its own routes documented can
// merge its own OpenAPI fragment with this one; nothing here forecloses that.

// openAPIDocument builds the OpenAPI 3.0 description of the gateway's own
// fixed REST surface.
func (app *App) openAPIDocument() map[string]any {
	paths := map[string]any{
		"/healthz": map[string]any{
			"get": operation("Health check", "Reports readiness and database connectivity.", nil, "OK", nil),
		},
		"/livez": map[string]any{
			"get": operation("Liveness check", "Always returns 200 once the process is running.", nil, "OK", nil),
		},
		"/api/v1/auth/register": map[string]any{
			"post": operation("Register", "Creates an account and, on a self-provisioning deployment, its tenant.",
				schemaRef("Credentials"), "Session issued", nil),
		},
		"/api/v1/auth/login": map[string]any{
			"post": operation("Login", "Exchanges credentials for a bearer token.",
				schemaRef("Credentials"), "Session issued", nil),
		},
		"/api/v1/me": map[string]any{
			"get":    operation("Current caller", "Returns the authenticated caller's subject.", nil, "Caller info", []string{"bearerAuth"}),
			"delete": operation("Delete my account", "Erases the caller's own personal data — a self-served data subject erasure request. Anonymizes rather than removes the row; see /api/v1/identities/{id} for the operator-initiated equivalent.", nil, "Deleted", []string{"bearerAuth"}),
		},
		"/api/v1/me/export": map[string]any{
			"get": operation("Export my data", "Returns everything this deployment holds on the caller's own account — a self-served data subject access request.", nil, "Account data", []string{"bearerAuth"}),
		},
		"/api/v1/auth/service-login": map[string]any{
			"post": operation("Service account login",
				"Exchanges a service account's API key for a bearer token. Unauthenticated like /auth/login: the key being presented is the credential. The tenant is the service account's own, fixed at creation — there is no tenant field to supply.",
				schemaRef("ServiceLogin"), "Session issued", nil),
		},
		"/api/v1/service-accounts": map[string]any{
			"post": operation("Create a service account",
				"The API key is generated by the server and returned exactly once, in this response.",
				schemaRef("CreateServiceAccount"), "Created, with its API key", []string{"bearerAuth"}),
			"get": operation("List service accounts", "Every service account owned by the caller's tenant.", nil, "Service accounts", []string{"bearerAuth"}),
		},
		"/api/v1/service-accounts/{id}": map[string]any{
			"delete": operation("Revoke a service account", "Deactivates it; past activity is preserved.", nil, "Revoked", []string{"bearerAuth"}),
		},
		"/api/v1/capabilities": map[string]any{
			"get": operation("List exposed capabilities",
				"Every capability a module explicitly published for external callers. Registration is not publication: an unexposed capability does not appear here even if some other module can call it. See ADR 0001.",
				nil, "Exposed capabilities", []string{"bearerAuth"}),
		},
		"/api/v1/capabilities/{ref}": map[string]any{
			"post": map[string]any{
				"summary": "Call a capability",
				"description": "Dispatches one capability by reference (\"name@version\"). The " +
					"payload is opaque JSON: the kernel does not know a module's contract " +
					"shape, only that a module claiming this capability agreed to handle " +
					"whatever this body decodes to. A module wanting a fully-typed REST " +
					"and OpenAPI surface for its own contract publishes its own proto or " +
					"schema alongside this generic one — that path is unaffected by this " +
					"endpoint existing. Tenant and caller identity come from the bearer " +
					"token, never from this body.",
				"security":   []map[string][]string{{"bearerAuth": {}}},
				"parameters": []map[string]any{pathParam("ref", "Capability reference as name@version, e.g. crm.contacts.list@v1")},
				"requestBody": map[string]any{
					"required": false,
					"content": map[string]any{
						"application/json": map[string]any{
							"schema": map[string]any{"type": "object", "description": "The capability's own request shape. Opaque to the kernel."},
						},
					},
				},
				"responses": map[string]any{
					"200": response("The capability's own response shape. Opaque to the kernel.", nil),
					"403": response("Unexposed or nonexistent — the two are indistinguishable, so this endpoint cannot be used to enumerate what a deployment runs internally.", nil),
				},
			},
		},
		"/api/v1/webhooks/endpoints": map[string]any{
			"post": operation("Register a webhook endpoint",
				"The signing secret is generated by the server and returned exactly once, in this response.",
				schemaRef("CreateWebhookEndpoint"), "Created, with its secret", []string{"bearerAuth"}),
			"get": operation("List webhook endpoints", "Every endpoint owned by the caller's tenant. Secrets are redacted.",
				nil, "Endpoints, secrets redacted", []string{"bearerAuth"}),
		},
		"/api/v1/webhooks/endpoints/{id}": map[string]any{
			"get":    operation("Get a webhook endpoint", "Secret included: this is a read the caller already owns.", nil, "Endpoint", []string{"bearerAuth"}),
			"patch":  operation("Update a webhook endpoint", "Fields omitted from the body are left unchanged.", schemaRef("UpdateWebhookEndpoint"), "Updated", []string{"bearerAuth"}),
			"delete": operation("Delete a webhook endpoint", "Delivery history is preserved.", nil, "Deleted", []string{"bearerAuth"}),
		},
		"/api/v1/webhooks/endpoints/{id}/rotate-secret": map[string]any{
			"post": operation("Rotate a webhook endpoint's secret", "The new secret is returned exactly once, in this response.", nil, "New secret", []string{"bearerAuth"}),
		},
		"/api/v1/webhooks/endpoints/{id}/replay": map[string]any{
			"post": operation("Replay dead deliveries", "Requeues every dead-lettered delivery for this endpoint.", nil, "Requeue count", []string{"bearerAuth"}),
		},
		"/api/v1/webhooks/endpoints/{id}/deliveries": map[string]any{
			"get": operation("List an endpoint's deliveries", "Most recent first.", nil, "Deliveries", []string{"bearerAuth"}),
		},
		"/api/v1/webhooks/deliveries/{id}/replay": map[string]any{
			"post": operation("Replay one delivery", "Refuses a delivery already marked delivered.", nil, "Replayed", []string{"bearerAuth"}),
		},
		"/api/v1/identities/{id}/roles": map[string]any{
			"post": operation("Assign a role", "Grants a role within the caller's own tenant. A duplicate grant is a no-op.", schemaRef("AssignRole"), "Assigned", []string{"bearerAuth"}),
			"get":  operation("List an identity's roles", "Roles held within the caller's own tenant.", nil, "Roles", []string{"bearerAuth"}),
		},
		"/api/v1/identities/{id}/roles/{role}": map[string]any{
			"delete": func() map[string]any {
				op := operation("Revoke a role", "", nil, "Revoked", []string{"bearerAuth"})
				op["parameters"] = []map[string]any{pathParam("role", "Role name")}
				return op
			}(),
		},
		"/api/v1/audit-events": map[string]any{
			"get": operation("Query the audit trail",
				"Compliance-grade security event log: authentication, service-account lifecycle, and role changes, scoped to the caller's own tenant. Filterable by actor_id and type; ordered most-recent-first.",
				nil, "Audit events", []string{"bearerAuth"}),
		},
		"/api/v1/identities/{id}/lock": map[string]any{
			"post": operation("Lock an account", "Blocks future logins and invalidates every session already issued to it, immediately.", nil, "Locked", []string{"bearerAuth"}),
		},
		"/api/v1/identities/{id}/unlock": map[string]any{
			"post": operation("Unlock an account", "Restores the ability to log in. Sessions invalidated by the lock are not restored.", nil, "Unlocked", []string{"bearerAuth"}),
		},
		"/api/v1/identities/{id}/revoke-sessions": map[string]any{
			"post": operation("Force logout everywhere", "Invalidates every session the account currently holds, without locking it — it may log in again immediately.", nil, "Revoked", []string{"bearerAuth"}),
		},
		"/api/v1/identities/{id}": map[string]any{
			"delete": operation("Delete an account", "Erases another account's personal data within the caller's own tenant — the operator-initiated counterpart to DELETE /api/v1/me, for a data subject access request on behalf of someone who can no longer sign in.", nil, "Deleted", []string{"bearerAuth"}),
		},
	}
	for path := range paths {
		if withParam, ok := paths[path].(map[string]any); ok {
			injectIDParam(path, withParam)
		}
	}

	if app.Auth.HasOIDC() {
		paths["/api/v1/oauth2/{provider}/authorize"] = map[string]any{
			"get": map[string]any{
				"summary":    "Start an OIDC login",
				"parameters": []map[string]any{pathParam("provider", "Configured OIDC provider name")},
				"responses":  map[string]any{"302": response("Redirect to the provider", nil)},
			},
		}
		paths["/api/v1/oauth2/{provider}/callback"] = map[string]any{
			"get": map[string]any{
				"summary":    "Complete an OIDC login",
				"parameters": []map[string]any{pathParam("provider", "Configured OIDC provider name")},
				"responses":  map[string]any{"200": response("Session issued", nil)},
			},
		}
	}

	if app.Auth.HasSAML() {
		paths["/api/v1/auth/saml/metadata"] = map[string]any{
			"get": map[string]any{
				"summary":   "This deployment's SAML SP metadata",
				"responses": map[string]any{"200": response("SAML metadata XML", nil)},
			},
		}
		paths["/api/v1/auth/saml/{idp}/login"] = map[string]any{
			"get": map[string]any{
				"summary":    "Start a SAML login",
				"parameters": []map[string]any{pathParam("idp", "Configured SAML identity provider name")},
				"responses":  map[string]any{"302": response("Redirect to the identity provider", nil)},
			},
		}
		paths["/api/v1/auth/saml/acs"] = map[string]any{
			"post": map[string]any{
				"summary":   "SAML Assertion Consumer Service",
				"responses": map[string]any{"200": response("Session issued", nil)},
			},
		}
	}

	return map[string]any{
		"openapi": "3.0.3",
		"info": map[string]any{
			"title":       "Sannad Gateway",
			"description": "The kernel's own fixed REST surface: auth, the generic capability bridge, and webhook management. A module's own capabilities are dispatched through /api/v1/capabilities/{ref} with a payload this document cannot describe further — see that endpoint's description.",
			"version":     "1",
		},
		"paths": paths,
		"components": map[string]any{
			"securitySchemes": map[string]any{
				"bearerAuth": map[string]any{"type": "http", "scheme": "bearer"},
			},
			"schemas": map[string]any{
				"Credentials": objectSchema(map[string]string{
					"email":    "string",
					"password": "string",
					"tenant":   "string",
				}, []string{"email", "password"}),
				"CreateWebhookEndpoint": objectSchema(map[string]string{
					"url":    "string",
					"events": "string",
				}, []string{"url"}),
				"UpdateWebhookEndpoint": objectSchema(map[string]string{
					"url":    "string",
					"events": "string",
					"active": "boolean",
				}, nil),
				"ServiceLogin": objectSchema(map[string]string{
					"api_key": "string",
				}, []string{"api_key"}),
				"CreateServiceAccount": objectSchema(map[string]string{
					"name": "string",
				}, []string{"name"}),
				"AssignRole": objectSchema(map[string]string{
					"role": "string",
				}, []string{"role"}),
			},
		},
	}
}

func operation(summary, description string, requestSchema map[string]any, responseDescription string, security []string) map[string]any {
	op := map[string]any{
		"summary":     summary,
		"description": description,
		"responses":   map[string]any{"200": response(responseDescription, nil)},
	}
	if requestSchema != nil {
		op["requestBody"] = map[string]any{
			"required": true,
			"content":  map[string]any{"application/json": map[string]any{"schema": requestSchema}},
		}
	}
	if len(security) > 0 {
		sec := make([]map[string][]string, len(security))
		for i, s := range security {
			sec[i] = map[string][]string{s: {}}
		}
		op["security"] = sec
	}
	return op
}

func response(description string, schema map[string]any) map[string]any {
	resp := map[string]any{"description": description}
	if schema != nil {
		resp["content"] = map[string]any{"application/json": map[string]any{"schema": schema}}
	}
	return resp
}

func schemaRef(name string) map[string]any {
	return map[string]any{"$ref": "#/components/schemas/" + name}
}

func objectSchema(fields map[string]string, required []string) map[string]any {
	props := make(map[string]any, len(fields))
	for name, kind := range fields {
		props[name] = map[string]any{"type": kind}
	}
	schema := map[string]any{"type": "object", "properties": props}
	if len(required) > 0 {
		schema["required"] = required
	}
	return schema
}

func pathParam(name, description string) map[string]any {
	return map[string]any{
		"name": name, "in": "path", "required": true,
		"description": description,
		"schema":      map[string]any{"type": "string"},
	}
}

// injectIDParam adds the {id} path parameter to every operation on a path
// that names one, so it is declared once here rather than repeated at every
// operation literal above.
func injectIDParam(path string, methods map[string]any) {
	if !pathHasIDParam(path) {
		return
	}
	for method, raw := range methods {
		op, ok := raw.(map[string]any)
		if !ok {
			continue
		}
		existing, _ := op["parameters"].([]map[string]any)
		op["parameters"] = append([]map[string]any{pathParam("id", "Resource ID")}, existing...)
		methods[method] = op
	}
}

func pathHasIDParam(path string) bool {
	return strings.Contains(path, "{id}")
}

// handleOpenAPI serves the document. Unauthenticated, like the health
// endpoints: a spec describing a REST surface is not itself the surface, and
// requiring a token to read API documentation is what sends an integrator to
// read source code instead.
func (app *App) handleOpenAPI(ctx *fiber.Ctx) error {
	return ctx.Status(fiber.StatusOK).JSON(app.openAPIDocument())
}
